[build]
  base = "/"
  publish = "dist"
  
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "8.19.3"
    STRIPE_SECRET_KEY = "@stripe_secret_key"
    SUCCESS_URL = "https://rarecollectables1.netlify.app/confirmation"
    CANCEL_URL = "https://rarecollectables1.netlify.app/cart"

  [functions]
    directory = "netlify/functions"
    node_bundler = "esbuild"

    [functions.node_version]
      version = "18"

    [functions.build]
      command = "npm install --legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' https://api.yourdomain.com; font-src 'self' https://fonts.gstatic.com; frame-src 'self' https://www.youtube.com; object-src 'none'; media-src 'self' data:; child-src 'self' https://www.youtube.com; worker-src 'self' blob:;"

[dev]
  command = "expo start --web"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

  [functions.node_version]
    version = "18"

  [functions.build]
    command = "npm install --legacy-peer-deps"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8.19.3"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' https://api.yourdomain.com; font-src 'self' https://fonts.gstatic.com; frame-src 'self' https://www.youtube.com; object-src 'none'; media-src 'self' data:; child-src 'self' https://www.youtube.com; worker-src 'self' blob:;"
