[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  base = "/"
  functions = "netlify/functions"

[dev]
  command = "expo start --web"

[build.environment]
  NODE_VERSION = "18"
  
[functions]
  directory = "netlify/functions"

  [functions.node_version]
    version = "18"

  [functions.build]
    command = "npm install"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' https://api.yourdomain.com; font-src 'self' https://fonts.gstatic.com; frame-src 'self' https://www.youtube.com; object-src 'none'; media-src 'self' data:; child-src 'self' https://www.youtube.com; worker-src 'self' blob:;"
