[build]
  base = "/"
  publish = "dist"
  
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "8.19.3"
    STRIPE_SECRET_KEY = "@stripe_secret_key"
    SUCCESS_URL = "https://rarecollectables1.netlify.app/confirmation"
    CANCEL_URL = "https://rarecollectables1.netlify.app/cart"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

  [functions.node_version]
    version = "18"

  [functions.build]
    command = "yarn install && yarn run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com https://m.stripe.network https://*.stripe.com https://api.hcaptcha.com; style-src 'self' 'unsafe-inline' https://*.stripe.com; img-src 'self' data: https://fhybeyomiivepmlrampr.supabase.co https://*.stripe.com; connect-src 'self' https://api.yourdomain.com https://fhybeyomiivepmlrampr.supabase.co https://*.stripe.com; font-src 'self' https://fonts.gstatic.com https://*.stripe.com; frame-src 'self' https://www.youtube.com https://*.stripe.com; object-src 'none'; media-src 'self' data:; child-src 'self' https://www.youtube.com https://*.stripe.com; worker-src 'self' blob:;"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"

[dev]
  command = "expo start --web"
